version: 'latest'

services:
  localstack:
    image: localstack/localstack
    container_name: ${PROJECT}-localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
      - ./localstack/files:/tmp/files
    networks:
      - backend

  malscanner:
    container_name: ${PROJECT}-malscanner
    image: ${PROJECT}-malscanner:latest
    ports:
      - "9000:8080"
    platform: linux/amd64
    build:
      context: ./packages/scanner
      dockerfile: Dockerfile
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=testUser
      - AWS_SECRET_ACCESS_KEY=testAccessKey
      - AWS_S3_BUCKET=uploads
      - AWS_S3_REGION=us-east-1
      - AWS_S3_ENDPOINT=http://localstack:4566
    volumes:
      - ./scanner:/var/task/src
      - /var/task/src/node_modules
    networks:
      - backend
    mem_limit: 1g
    cpus: 2

networks:
  backend: {}
